# Configuration related to self-hosted runner.
self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - self-hosted
    - arc-runner-set
    - arc-runner-set-my-image
    - arc-runner-set-latest-image
