apiVersion: v1
kind: Pod
metadata:
  name: hari-test-feb2026-spyre-dev-pf
spec:
  # restartPolicy: Always
  # serviceAccountName: default
  imagePullSecrets:
    - name: wxpe-cicd-vllm-iccr-internal
    - name: all-icr-io-cil15-2
  schedulerName: spyre-scheduler
  containers:
    - name: app
      resources:
        limits:
          ibm.com/spyre_pf: '1'
        requests:
          ibm.com/spyre_pf: '1'
      terminationMessagePath: /dev/termination-log
      command:
        - bash
        - -c
        - tail -f /dev/null
      env:
        # - name: HF_HOME
        #   value: /home/myhomeworkdir/
        - name: FLEX_COMPUTE
          value: SENTIENT
        - name: FLEX_DEVICE
          value: PF
        - name: TOKENIZERS_PARALLELISM
          value: 'false'
        - name: AIU_SETUP_MULTI_AIU
          value: '1'
      # securityContext:
      #   capabilities:
      #     drop:
      #       - ALL
      #   runAsNonRoot: true
      #   allowPrivilegeEscalation: false
      # image: 'us.icr.io/wxpe-cicd-internal/amd64/torch-aiu-runtime-dev:latest'
      # image: 'ubuntu:24.04'
      # image: 'us.icr.io/cil15-shared-registry/mytestghrunner:v1'
      # image: 'us.icr.io/cil15-shared-registry/mytestghrunner:v2'
      # image: 'us.icr.io/cil15-shared-registry/mytestghrunner:v3'
      image: us.icr.io/cil15-shared-registry/mytestghrunner:v4
      imagePullPolicy: Always
      volumeMounts:
        - name: dev-shm
          mountPath: /dev/shm
        - name: shared-models-pvc
          mountPath: /pvc-shared-models-pvc
      terminationMessagePolicy: File
      # workingDir: /home/myhomeworkdir
  serviceAccount: default
  volumes:
    - name: dev-shm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi
    - name: shared-models-pvc
      persistentVolumeClaim:
        claimName: shared-models
