name: Actions Runner Controller Demo
on:
  workflow_dispatch: null

jobs:
  Explore-GitHub-Actions:
    runs-on: hb-test-org-runners-2
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
